export const MUTATION_TYPES = {
    USER:{
        SET_USER:'SET_USER',
        SET_FRIENDS:'SET_FRIENDS',
        SET_MESSAGES:'SET_MESSAGES',
        ADD_FRIEND:'ADD_FRIEND',
        SET_FRIENDS_LOADING:'SET_FRIENDS_LOADING',
        SET_MESSAGES_LOADED:'SET_MESSAGES_LOADED'

    }
}